# Generated by Django 3.0.1 on 2022-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllVehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('mc', 'Motor cycle'), ('c', 'Car'), ('tr', 'Truck'), ('bc', 'bycycle'), ('ar', 'auto rickshaw')], max_length=150)),
                ('t_type', models.CharField(choices=[('el', 'electrical'), ('pl', 'petrol'), ('dl', 'diesel')], max_length=150)),
                ('v_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('v_img', models.ImageField(blank=True, upload_to='vehicle<django.db.models.fields.CharField>')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published', models.DateField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('v_name',),
            },
        ),
    ]
