# Generated by Django 3.0.1 on 2022-04-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_auto_20220429_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allvehicles',
            old_name='v_type',
            new_name='vehicletype',
        ),
    ]
