# Generated by Django 3.0.1 on 2022-04-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0003_auto_20220429_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allvehicles',
            name='vehicletype',
            field=models.CharField(choices=[('Motor cycle', 'Motor cycle'), ('Car', 'Car'), ('Truck', 'Truck'), ('bycycle', 'bycycle'), ('auto rickshaw', 'auto rickshaw')], max_length=150),
        ),
    ]
